var links = new Array();
links[0] = "https://youtu.be/tzD9OxAHtzU?si=87L7Kzrm6UxvuZR3";
links[1] = "https://youtu.be/AnoTVNqLJ-Q?si=x_6o5DbrEeZ3_gXd";
links[2] = "https://youtu.be/brGo1JgwtrM?si=kg7DA9BLu1GGrafG";
links[3] = "https://youtu.be/UvFroPxa67s?si=m-jJuT8bO9R94dhT";
links[4] = "https://youtu.be/9S8yAqINOYs?si=N5s1RI1YDCeMIt-W";
links[5] = "https://youtu.be/iQWY6j4aGc8?si=AWQCS4n4DK9tMOn0";
links[6] = "https://youtu.be/wVNMVGY56Os?si=XFLmqwA7H1ciCvSl";
links[7] = "https://youtu.be/ImL2oQ_FxfU?si=4YVphgt0wKGYs5h2";
links[8] = "https://youtu.be/U_lrep5F8gE?si=_AVJe0fLV0HlNLK4";
links[9] = "https://youtu.be/OHj0icF52tQ?si=-mz8iG9x7iHk3_pU";
links[10] = "https://youtu.be/BZkiIPSoLZU?si=dEvgqReIoTsdg3vb";
links[11] = "https://youtu.be/FvwI98sbSZY?si=cQesn7n-adLNj5sU";
links[12] = "https://youtu.be/O5rYYx1iuvM?si=SrUHD9sPNuZY5LRf";
links[13] = "https://youtu.be/PjW1-4MWBUE?si=7o-ntViy6sNaJz_K";
links[14] = "https://youtu.be/7UBsDEg9wLY?si=wfjWYXiDhAvMdX0d";
links[15] = "https://youtu.be/Yd0qsSLqmpI?si=u3CzTd-9hrqS1i0d";
links[16] = "https://youtu.be/jCHDHuO5Pq8?si=E-5NL3ap4bo4O-7O";
links[17] = "https://youtu.be/KUhpj5dQack?si=84JJ63TDfMV1Z03w";
links[18] = "https://youtu.be/HCkpPXrZ7x4?si=bJbSQrlBV6HxIa4y";
links[19] = "https://youtu.be/OL9K-3L_7D0?si=DyPZOnmM7LNUGNXd";
links[20] = "https://youtu.be/8HnRi6VOKCc?si=IY71Z8-9n9czb1a_";
links[21] = "https://youtu.be/PEPnf8riCck?si=-q7JCRFJMGWAojdr";
links[22] = "https://youtu.be/ss7PwhXgwbA?si=gvHJYu5TFfUX1Xth";
links[23] = "https://youtu.be/d9z9J4Wz6Ns?si=1EJa8sLb8dO125sL";
links[24] = "https://youtu.be/8GxDwN5Ssyk?si=lwS6jJTbXcPnBbVu";
links[25] = "https://youtu.be/8GxDwN5Ssyk?si=hZxzsHs1Izz2h7HN";
links[26] = "https://youtu.be/iBm_NSjPwCc?si=1PnmquOvI89blOJk";
links[27] = "https://youtu.be/1cNY9vus2MI?si=bbanLtbKA8uRq1cP";
links[28] = "https://youtu.be/OKgN-spo_l8?si=2HHz7iQVamGQZi8W";
links[29] = "https://youtu.be/sWGxTqLpngo?si=NRtJo39gKDaD1GtU";
links[30] = "https://youtu.be/AXihAMb_cv8?si=-B8rijLkTMtgpBVr";
links[31] = "https://youtu.be/z8_jQD4F1aE?si=9Ybsdum_CH_jGH_X";
links[32] = "https://youtu.be/7HwU6Lb92u0?si=AZQGqevX3JMhkdCm";
links[33] = "https://youtu.be/qf5_oMc924w?si=oyElPqTTIu2SaabO";
links[34] = "https://youtu.be/57y7DjoanPI?si=DXz3ta8yfrrnpf6r";
links[35] = "https://youtu.be/jloLwET97nE?si=kcpi85j3_qu-Pv31";
links[36] = "https://youtu.be/rIB3khGCA2M?si=qChcQLGB6XVe1Z5u";
links[37] = "https://youtu.be/-Wkva1SGLOE?si=mDU-mLX7k45apMlM";
links[38] = "https://youtu.be/vpysNcXpa2o?si=3Zuq4IXXgPCBNpdm";
links[39] = "https://youtu.be/JKiUUwoVm3g?si=v8l_l_qjJtXW5Rby";
links[40] = "https://youtu.be/VLuc2Ubt5Xc?si=xihaHXh51kRQTmHd";
links[41] = "https://youtu.be/DzsNFEWklnM?si=gBNsjuKuZcNK7BpE";
links[42] = "https://youtu.be/y4QKHuG4QCg?si=2ep2lgV8B_a0nbMI";
links[43] = "https://youtu.be/60npBvKvGBA?si=K0JVktZZvFBSrZJI";
links[44] = "https://youtu.be/5UaAZGteBPg?si=5dx4LuS6oWdhGqDz";
links[45] = "https://youtu.be/AySjtkg4X6Q?si=BvBi-5kXM6vXAsFb";
links[46] = "https://youtu.be/0c2vjcsDB8U?si=XEQQaHt0f2iAsigM";
links[47] = "https://youtu.be/bxJg8zhXCjY?si=2XY3xH4iWH7I3hqL";
links[48] = "https://youtu.be/z4joadXXNZA?si=fQBDuJFIEzmj_ONc";
links[49] = "https://youtu.be/WkHrFn4Fx6Q?si=kXY5ByJJLq_8L9uB";
links[50] = "https://youtu.be/tDpdOQfWPBQ?si=X1LN-6wM1M_UYDuz";
links[51] = "https://youtu.be/gSLGgTcvzsE?si=9dJ3xbi00aiXivHr";
links[52] = "https://youtu.be/CfpRuNaduEs?si=lcl1eSs7X46HhzLU";
links[53] = "https://youtu.be/HhKzRsP1Wc0?si=mh93n7Uc5B1HeJWH";
links[54] = "https://youtu.be/zXk6GiWTxgc?si=iQ8CqlznM7pGgkiy";
links[55] = "https://youtu.be/Ll4DRoANaVA?si=uTR8aGwvLrpryklH";
links[56] = "https://youtu.be/c_pCHNGfcHk?si=-i-fQbKSQwvSI67j";
links[57] = "https://youtu.be/qmvDrQoLz8g?si=JFQKwqPLY3dGZGER";
links[58] = "https://youtu.be/L9iUor7s2MM?si=KBIs9PaVGEx87Jql";
links[59] = "https://youtu.be/T-sJFwirHik?si=3XnEzxAVSPbheJI1";
links[60] = "https://youtu.be/RgmEZUTDXJk?si=S08ET0Okhh2NSsua";
links[61] = "https://youtu.be/-FyR3FfjS6s?si=xXNVdBSknXhqFLAH";
links[62] = "https://youtu.be/uz0WytEk7UY?si=K1Q_AFqIOEBuVH2g";
links[63] = "https://youtu.be/gnzJFx2vDBY?si=GHL4K8gNeMHfMJNT";
links[64] = "https://youtu.be/fpk6itC2Pq0?si=Nk9M8AdQ1-dljyJu";
links[65] = "https://youtu.be/-BXItmWzWNE?si=11pxaFrzPhvVuhg9";
links[66] = "https://youtu.be/jjy0bIO-YNI?si=azsw5SO3DTEivmx3";
links[67] = "https://youtu.be/v7HFWmuf6SQ?si=CO0NLfUgP8mQ9eMi";
links[68] = "https://youtu.be/wGc0jClpTPQ?si=Xu0CKLbrV7Zwsnta";
links[69] = "https://youtu.be/PLUhJmqHd1s?si=Zr6G1EZusG2rigBA";
links[70] = "https://youtu.be/aFvw_yu0N3A?si=INqu1VVzt0Td99Iz";
links[71] = "https://youtu.be/d7DdLRe5QgM?si=Xb08NUcFaW0L2B_D";
links[72] = "https://youtu.be/AJZIwDbJxPA?si=GUiunYOAico03k5c";

function randomSkibidiEpisode() {
  // Chooses a random link:
  var i = Math.floor(Math.random() * links.length);
  // Directs the browser to the chosen target:
  window.open(links[i])
  return false;
}
untitledFunction();